### ISSUE TITLE
bug: hide-create-button patch causes startup crash

### ISSUE THREAD

**Issue by l4v3nx** [ReVanced/revanced-patches-template#825]
### Type

Other

### Bug description

hide create button causes crash at startup. tested and confirmed in log

### Steps to reproduce

also I used cli 2.14.0, patches 2.85 and integrations 0.54.0. also I use evolutionx rom 7.2 android 13, 20 oct build, device: poco x3 pro
1. start building revanced as usual
2. include hide-create-button patch
3. expect crash after building and mounting

### Relevant log output

```shell
time: 1666292481733
msg: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
stacktrace: arjx: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
	at arle.a(PG:2)
	at armd.b(PG:3)
	at armd.tl(PG:5)
	at arzw.tl(PG:5)
	at asby.run(PG:4)
	at aeaq.run(PG:2)
	at ashm.run(PG:2)
	at asho.run(PG:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
	at app.revanced.integrations.patches.HideCreateButtonPatch.hideCreateButton(HideCreateButtonPatch.java:38)
	at kzw.z(PG:31)
	at kyt.a(PG:45)
	at armd.tl(PG:2)
	... 13 more
```

### Solution

exclude hide-create-button from patch list while building.

### Additional context

btw, I tried to patch revanced on android_x86 (blissos 11.14) vm and suddenly it works even with this patch

**Comment by Infinitytreacher** [comment]
I am having the same problem revanced crashes at start, I have included hides created button patch and have patched with the compatible version 17.36.37

**Comment by old4error** [comment]
> Are you patching a compatible version of the app?

yes, 17.36.37

> Also which patches version was the last time it worked?
I usually choose all patches except microg, hide cast button, theme, premium banner and debugging. if I also choose hide create button, it crashes; if not, it works

**Comment by old4error** [comment]
I guess it's 2.83 because I don't remember I chose hide mix patch

**Comment by oSumAtrIX** [comment]
@old4error exclude all patches except for the failing patch, if it doesn't fail, report back with the patch which conflicts and causes it to fail

**Comment by E85Addict** [comment]
Having the same issue, same error message, only happens on root install, but for some reason unrooted works fine.

**Comment by old4error** [comment]
unroot version 17.36.37 patches 2.85 cli 2.14 integr. 0.54:
no crash without hide-create-button patch, also there is no create button (when logged out) when logged in - crash
root version, same versions as above: included all patches (except hide-cast and microg for root build) except hide-create-button patch: no crash; with hide-create-button patch - crash

**Comment by E85Addict** [comment]
> unroot version 17.36.37 patches 2.85 cli 2.14 integr. 0.54: no crash without hide-create-button patch, also there is no create button (when logged out) when logged in - crash root version, same versions as above: included all patches (except hide-cast and microg for root build) except hide-create-button patch: no crash; with hide-create-button patch - crash

Also having the same results here, seems as having the create button appear is causing the crash which is odd, because I don't think anythings changed with that patch.

**Comment by oSumAtrIX** [comment]
Root or not does not change the patch process, please record as mentioned.

**Comment by old4error** [comment]
root version 17.36.37 patches 2.85 cli 2.14 integr. 0.54:
included all patches except hide-create-button patch: no crash; with hide-create-button patch - crash

**Comment by old4error** [comment]
if including only hide-create-button patch - no crash

**Comment by oSumAtrIX** [comment]
Find and report back with the patch which conflicts with the patch.

**Comment by Infinitytreacher** [comment]
If it helps, everything worked fine with 2.83.2 with the following patches on 17.36.37 built using revanced builder on termux-

> hide-shorts-button
> hide-create-button
> disable-startup-shorts-player
> hide-cast-button
> sponsorblock
> hide-autoplay-button
> return-youtube-dislike
> theme
> hide-email-address
> hide-watermark
> custom-branding
> premium-heading
> old-quality-layout
> general-ads
> video-ads
> swipe-controls
> downloads
> settings
> microg-support
> custom-video-buffer
> client-spoof
> always-autorepeat
> remember-video-quality
> minimized-playback
> custom-playback-speed

Seeing the recent versions having changes only to video-ads  I tried coupling video-ads and hides created button but that worked fine to my surprise.

**Comment by Rikysonic** [comment]
I can confirm crash when hide-create-button patch is selected.

**Comment by DerivativeOfLog7** [comment]
Can confirm the same issue with patches v2.85.1, root, compiled excluding microg-support

```
10-21 15:50:24.697 27626 27626 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-21 15:50:24.700 27626 27626 I AndroidRuntime: Using default boot image
10-21 15:50:24.700 27626 27626 I AndroidRuntime: Leaving lock profiling enabled
10-21 15:50:25.133 27626 27626 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-21 15:50:25.216 27652 27652 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-21 15:50:25.217 27626 27626 D AndroidRuntime: Shutting down VM
10-21 15:50:25.219 27652 27652 I AndroidRuntime: Using default boot image
10-21 15:50:25.219 27652 27652 I AndroidRuntime: Leaving lock profiling enabled
10-21 15:50:25.628 27652 27652 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-21 15:50:25.700 27652 27652 D AndroidRuntime: Shutting down VM
10-21 15:50:26.290 27671 27671 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-21 15:50:26.293 27671 27671 I AndroidRuntime: Using default boot image
10-21 15:50:26.293 27671 27671 I AndroidRuntime: Leaving lock profiling enabled
10-21 15:50:26.714 27671 27671 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-21 15:50:26.786 27671 27671 D AndroidRuntime: Shutting down VM
10-21 15:50:27.359 27754 27754 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-21 15:50:27.361 27754 27754 I AndroidRuntime: Using default boot image
10-21 15:50:27.361 27754 27754 I AndroidRuntime: Leaving lock profiling enabled
10-21 15:50:27.786 27754 27754 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-21 15:50:27.867 27754 27754 D AndroidRuntime: Shutting down VM
10-21 15:50:28.437 27806 27806 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-21 15:50:28.439 27806 27806 I AndroidRuntime: Using default boot image
10-21 15:50:28.439 27806 27806 I AndroidRuntime: Leaving lock profiling enabled
10-21 15:50:28.874 27806 27806 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-21 15:50:28.953 27806 27806 D AndroidRuntime: Shutting down VM
10-21 15:50:29.501 27860 27860 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-21 15:50:29.503 27860 27860 I AndroidRuntime: Using default boot image
10-21 15:50:29.503 27860 27860 I AndroidRuntime: Leaving lock profiling enabled
10-21 15:50:29.945 27860 27860 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-21 15:50:30.035 27860 27860 D AndroidRuntime: Shutting down VM
10-21 15:50:30.582 27891 27891 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-21 15:50:30.585 27891 27891 I AndroidRuntime: Using default boot image
10-21 15:50:30.585 27891 27891 I AndroidRuntime: Leaving lock profiling enabled
10-21 15:50:31.000 27599 27599 E AndroidRuntime: FATAL EXCEPTION: main
10-21 15:50:31.000 27599 27599 E AndroidRuntime: Process: com.google.android.youtube, PID: 27599
10-21 15:50:31.000 27599 27599 E AndroidRuntime: arjx: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
10-21 15:50:31.000 27599 27599 E AndroidRuntime:        at arle.a(PG:2)
10-21 15:50:31.000 27599 27599 E AndroidRuntime:        at armd.b(PG:3)
10-21 15:50:31.000 27599 27599 E AndroidRuntime:        at armd.tl(PG:5)
10-21 15:50:31.000 27599 27599 E AndroidRuntime:        at arzw.tl(PG:5)
10-21 15:50:31.000 27599 27599 E AndroidRuntime:        at asby.run(PG:4)
10-21 15:50:31.000 27599 27599 E AndroidRuntime:        at aeaq.run(PG:2)
10-21 15:50:31.000 27599 27599 E AndroidRuntime:        at ashm.run(PG:2)
10-21 15:50:31.000 27599 27599 E AndroidRuntime:        at asho.run(PG:2)
10-21 15:50:31.000 27599 27599 E AndroidRuntime:        at android.os.Handler.handleCallback(Unknown Source:2)
10-21 15:50:31.000 27599 27599 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Unknown Source:4)
10-21 15:50:31.000 27599 27599 E AndroidRuntime:        at android.os.Looper.loopOnce(Unknown Source:176)
10-21 15:50:31.000 27599 27599 E AndroidRuntime:        at android.os.Looper.loop(Unknown Source:76)
10-21 15:50:31.000 27599 27599 E AndroidRuntime:        at android.app.ActivityThread.main(Unknown Source:138)
10-21 15:50:31.000 27599 27599 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-21 15:50:31.000 27599 27599 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
10-21 15:50:31.000 27599 27599 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(Unknown Source:309)
10-21 15:50:31.000 27599 27599 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
10-21 15:50:31.000 27599 27599 E AndroidRuntime:        at app.revanced.integrations.patches.HideCreateButtonPatch.hideCreateButton(HideCreateButtonPatch.java:38)
10-21 15:50:31.000 27599 27599 E AndroidRuntime:        at kzw.z(PG:31)
10-21 15:50:31.000 27599 27599 E AndroidRuntime:        at kyt.a(PG:45)
10-21 15:50:31.000 27599 27599 E AndroidRuntime:        at armd.tl(PG:2)
10-21 15:50:31.000 27599 27599 E AndroidRuntime:        ... 13 more
10-21 15:50:31.008 27891 27891 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-21 15:50:31.089 27891 27891 D AndroidRuntime: Shutting down VM
```

**Comment by DerivativeOfLog7** [comment]
hide-shorts-button doesn't seem to cause any issues for me

**Comment by oSumAtrIX** [comment]
Fixed.
